NewsPaper/NewsPaper/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news.urls')),
    path('accounts/', include('allauth.urls'), name='accounts'),
]

NewsPaper/news/urls.py
from django.urls import path
from .views import PostList, PostDetail, PostSearch, PostUpdateView, PostCreateView, PostDeleteView, upgrade_me, ProfileView, HomeView


app_name = 'news'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('news/', PostList.as_view(), name='all_posts'),
    path('news/<int:pk>', PostDetail.as_view(), name='postDetail'),
    path('news/search', PostSearch.as_view(), name='post_search' ),

    path('news/add', PostCreateView.as_view(), name='post_create'),
    path('news/<int:pk>/edit', PostUpdateView.as_view(), name='post_update'),
    path('news/<int:pk>/delete', PostDeleteView.as_view(), name='post_delete'),
    path('upgrade/', upgrade_me, name = 'upgrade'),
    path('profile/', ProfileView.as_view(), name='profile'),
]

NewsPaper/templates/layout/parts/footer.html
<footer class="footer mt-auto py-3 bg-light">
    <div class="container">
      <span class="text-muted">Place sticky footer content here.</span>
    </div>
   </footer>

NewsPaper/templates/layout/parts/header.html
<header class="p-3 text-bg-dark">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
          <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"/></svg>
        </a>
   
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href='{% url "news:home" %}' class="nav-link px-2 text-white">Home</a></li>
          <li><a href='{% url "news:all_posts" %}' class="nav-link px-2 text-white">News</a></li>
          <li><a href='{% url "news:post_search" %}' class="nav-link px-2 text-white">Search</a></li>
          <li><a href='{% url "news:post_create" %}' class="nav-link px-2 text-white">Add news</a></li>
        </ul>
        {% if request.user.is_authenticated %}
        <div class="text-end">
          <a href="{% url 'news:profile' %}" class="btn btn-outline-light me-2">Profile</a>
          <a href='/accounts/logout/' type="button" class="btn btn-warning">Logout</a>
          {% if is_not_authors %}
          <a class="btn btn-info" href="{% url 'news:upgrade' %}">
            Стать автором
           </a>
           {% endif %}
        </div>
        {% else %}
        <div class="text-end">
          <a href='/accounts/login/' class="btn btn-outline-light me-2">Login</a>
          <a href='/accounts/signup/' type="button" class="btn btn-warning">Sign-up</a>
        {% endif %}
      </div>
    </div>
   </header>