NewsPaper/NewsPaper/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news.urls')),
    path('accounts/', include('allauth.urls'), name='accounts'),
]

NewsPaper/news/urls.py
from django.urls import path
from .views import PostList, PostDetail, PostSearch, PostUpdateView, PostCreateView, PostDeleteView, upgrade_me, ProfileView, HomeView


app_name = 'news'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('news/', PostList.as_view(), name='all_posts'),
    path('news/<int:pk>', PostDetail.as_view(), name='postDetail'),
    path('news/search', PostSearch.as_view(), name='post_search' ),

    path('news/add', PostCreateView.as_view(), name='post_create'),
    path('news/<int:pk>/edit', PostUpdateView.as_view(), name='post_update'),
    path('news/<int:pk>/delete', PostDeleteView.as_view(), name='post_delete'),
    path('upgrade/', upgrade_me, name = 'upgrade'),
    path('profile/', ProfileView.as_view(), name='profile'),
]

NewsPaper/news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum
from django.db.models.functions import Left


class Author(models.Model):
    authorUser = models.OneToOneField(User, on_delete=models.CASCADE)
    authorRating = models.IntegerField(default=0)

    def __str__(self) -> str:
        return self.authorUser.username
    
    def update_rating(self):
        postRating = self.post_set.all().aggregate(pRating=Sum('rating'))
        postRat = 0
        postRat += postRating.get('pRating')

        commentRating = self.authorUser.comment_set.all().aggregate(cRating=Sum('rating'))
        comRat = 0
        comRat += commentRating.get('cRating')

        self.authorRating = postRat * 3
        self.save()


class Category(models.Model):
    categoryName = models.CharField(max_length=255, unique = True)

    def __str__(self) -> str:
        return self.categoryName


class Post(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    NEWS = 'NW'
    ARTICLE = 'AR'
    category_choises = (
        (NEWS, 'Новость'),
        (ARTICLE, 'Статья'),
    )
    categoryType = models.CharField(max_length=2, choices=category_choises, default= ARTICLE)
    creationData = models.DateTimeField(auto_now_add=True)
    postCategory = models.ManyToManyField(Category, through='PostCategory')
    title = models.CharField(max_length=255)
    text = models.TextField()
    rating = models.SmallIntegerField(default=0)

    def __str__(self) -> str:
        return self.title

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        return self.text[0:123] + '...' 
    
    def get_absolute_url(self):
        return f'/news/{self.id}'
    


class PostCategory(models.Model):
    postThrough = models.ForeignKey(Post, on_delete=models.CASCADE)
    categoryThrough = models.ForeignKey(Category, on_delete=models.CASCADE)


class Comment(models.Model):
    commentPost = models.ForeignKey(Post, on_delete=models.CASCADE)
    commentUser = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    creationDate = models.DateTimeField(auto_now_add=True)
    rating = models.IntegerField(default=0)

    def __str__(self):
        return self.commentUser.username

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

NewsPaper/news/forms.py
from django.forms import ModelForm
from allauth.account.forms import SignupForm, LoginForm
from django.contrib.auth.models import Group
from django import forms
from .models import Post

class PostForm(ModelForm):
    
    class Meta:
        model = Post
        fields = ("author", "title", "categoryType", 'text')
        widgets = {
            'author': forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Enter your name'
            }),
            'title': forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Enter title'
            }),
            'categoryType': forms.Select(attrs={
            'class': 'form-control',
            }),
            'text': forms.Textarea(attrs={
            'class': 'form-control',
            }),
        }


class BasicSignupForm(SignupForm):
    email = forms.EmailField(widget=forms.TextInput(attrs={'placeholder': 'Email', 'class':'form-control',}))
  
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["password1"].widget.attrs.update({"class": "form-control"})
        self.fields["password2"].widget.attrs.update({"class": "form-control"})
    
  
    def save(self, request):
        user = super(BasicSignupForm, self).save(request)
        basic_group = Group.objects.get_or_create(name='common')[0]
        basic_group.user_set.add(user)
        return user
    

class BasicLoginForm(LoginForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))
            
    def __init__(self, *args, **kwargs):
        super(BasicLoginForm, self).__init__(*args, **kwargs)
        self.fields['login'].widget = forms.TextInput(attrs={'class':'form-control'})

    def save(self, request):
        user = super(BasicLoginForm, self).save(request)
        basic_group = Group.objects.get_or_create(name='common')[0]
        basic_group.user_set.add(user)
        return user

NewsPaper/news/views.py
from django.shortcuts import render
from django.views import View
from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView
from django.core.paginator import Paginator
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView
from django.urls import reverse_lazy
from .filters import PostFilter
from .forms import PostForm
from .models import Post, Author
from django.shortcuts import redirect
from django.contrib.auth.models import Group
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import PermissionRequiredMixin



class PostList(ListView):
    model = Post
    ordering = ['-creationData']
    template_name = 'post/posts.html'
    context_object_name = 'posts'
    paginate_by = 2

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
        return super().get(request, *args, **kwargs)
    

class PostSearch(ListView):
    model = Post
    ordering = ['-creationData']
    template_name = 'post/post_search.html'
    context_object_name = 'post_search'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = PostFilter(self.request.GET, queryset = self.get_queryset())
        context['form'] = PostForm()
        return context


class PostDetail(DetailView):
    model = Post
    template_name = 'post/post.html'
    context_object_name = 'post'
    queryset = Post.objects.all()


class PostCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Post
    template_name = 'post/post_create.html'
    permission_required = ('news.add_post',
                            'news.change_post')
    permission_denied_message = 'Чтобы создавать новости, необходимо стать автором'
    form_class = PostForm


class PostUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    template_name = 'post/post_create.html'
    permission_required = ('news.add_post',
                            'news.change_post')
    permission_denied_message = 'Чтобы редактировать новости, необходимо стать автором'
    form_class = PostForm

    def get_object(self, **kwargs):
       id = self.kwargs.get('pk')
       return Post.objects.get(pk=id)


class PostDeleteView(DeleteView):
    template_name = 'post/post_delete.html'
    queryset = Post.objects.all()
    success_url = reverse_lazy('news:all_posts')


class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'profile/profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_not_authors'] = not self.request.user.groups.filter(name = 'authors').exists()
        return context
    
@login_required
def upgrade_me(request):
    user = request.user
    Author.objects.create(authorUser=user)
    premium_group = Group.objects.get(name='authors')
    if not request.user.groups.filter(name='authors').exists():
        premium_group.user_set.add(user)
    return redirect('/news/')


class HomeView(TemplateView):
    template_name = 'post/home_page.html'

NewsPaper/news/templates/post/home_page.html
{% extends 'layout/base.html' %}
{% load custom_filters %} 

{% block title %}
News
{% endblock title %}

{% block content %}
<h1>Home page</h1>
{% endblock content%}

NewsPaper/news/templates/post/post.html
{% extends 'layout/base.html' %}
{% load custom_filters %}
{% block title %}
News | {{ post.title }}
{% endblock title %}
{% block content %}
<div>
    <h2>{{ post.title|Censor }}</h2>
    <p> {{ post.creationData|date:'d F Y, H:i' }} </p>
    <p> {{ post.text|Censor }} </p>
    <nav class='nav justify-content-end'>
        <a class='nav-link' href="{% url 'news:post_update' post.id %}">
            Update
        </a>
        <a class='nav-link' href="{% url 'news:post_delete' post.id %}">
            Delete
        </a>
    </nav>
</div>
<hr>
{% endblock content %}

NewsPaper/news/templates/post/post_create.html
{% extends 'layout/base.html' %}


{% block title %}
News | Create
{% endblock title %}

{% block content %}

<h3>News Information</h3>

<form method="POST">
 {% csrf_token %}
 {{ form }}
   <input class="btn btn-success" type="submit" value="Add">
</form>

{% endblock content %}

NewsPaper/news/templates/post/post_delete.html
{% extends 'layout/base.html' %}


{% block title %}
News | delete
{% endblock title %}

{% block content %}

<h3>Delete this News?</h3>
<div class="card">
 <div class="card-header">
   <h3>
     {{ post.title }}
   </h3>
 </div>
 <div class="card-body">
   {{ post.text }}
 </div>
</div>
<form method="POST">
 {% csrf_token %}
   <input class="btn btn-success" type="submit" value="Delete">
</form>

{% endblock content %}

NewsPaper/news/templates/post/post_search.html
{% extends 'layout/base.html' %}
{% load custom_filters %} 

{% block title %}
News | Search
{% endblock title %}

{% block content %}
<h1>Поиск</h1>
<hr>
{% if post_search %}

<form method="GET">
    {{ filter.form }}
    <input class="btn btn-dark" type="submit" value="Найти">
 </form>
 
    {% comment %} {% for post in posts %} {% endcomment %}
    {% for post in filter.qs %}
        <div class="card">
            <div class="card-header">
                <h2><a href="{% url 'news:postDetail' post.pk %}">{{ post.title|Censor }}</a></h2>
                <p> {{ post.creationData|date:'d F Y, H:i' }} </p>
            </div>
            <div class="card-body">
                <p> {{ post.text|truncatechars:50 |Censor }} </p>
                <nav class='nav justify-content-end'>
                    <a class='nav-link' href="{% url 'news:post_update' post.id %}">
                        Update
                    </a>
                    <a class='nav-link' href="{% url 'news:post_delete' post.id %}">
                        Delete
                    </a>
                </nav> 
            </div> 
        </div>
        <hr>
    {% endfor %}

    {% include "post/parts/paginator.html" %}

{% else %}
    <h2>Постов нет</h2>
{% endif %}
{% endblock content %}

NewsPaper/news/templates/post/posts.html
{% extends 'layout/base.html' %}
{% load custom_filters %} 

{% block title %}
News
{% endblock title %}


{% block content %}
<h1>Все новости</h1>
<hr>
{% if posts %}

    {% for post in posts %}
    {% comment %} {% for post in filter.qs %} {% endcomment %}

        <div class="card">
            <div class="card-header">
                <h2><a href="{% url 'news:postDetail' post.pk %}">{{ post.title|Censor }}</a></h2>
                <p> {{ post.creationData|date:'d F Y, H:i' }} </p>
            </div>
            <div class="card-body">
                <p> {{ post.text|truncatechars:50 |Censor }} </p>
                <nav class='nav justify-content-end'>
                    <a class='nav-link' href="{% url 'news:post_update' post.id %}">
                        Update
                    </a>
                    <a class='nav-link' href="{% url 'news:post_delete' post.id %}">
                        Delete
                    </a>
                </nav>
            </div> 

        </div>
        <hr>
    {% endfor %}

    {% include "post/parts/paginator.html" %}

{% else %}
    <h2>Постов нет</h2>
{% endif %}
{% endblock content %}